version: '3'
services:
  
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/baal/nginx/conf.d:/etc/nginx/conf.d
      - /home/baal/nginx/ssl:/etc/ssl
      - /home/baal/nginx/www:/var/www
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
  plex:
    image: linuxserver/plex
    container_name: plex
    restart: always
    network_mode: host
    env_file:
      - /home/baal/config/docker.env
    volumes:
      - /home/baal/plex/config:/config
      - /home/baal/plex/tv:/data/tvshows
      - /home/baal/plex/movies:/data/movies
      - /home/baal/plex/music:/data/music
      - /home/baal/plex/transcode:/data/transcode